In [2]:
# @title
from google.colab import files

uploaded = files.upload()

file_name = None
if uploaded:
  for fn in uploaded.keys():
    print(f'Fichier "{fn}" téléchargé.')
    file_name = fn
else:
  print("Aucun fichier n'a été téléchargé. Veuillez le télécharger manuellement ou exécuter cette cellule à nouveau.")
  # @title
import pandas as pd
df = pd.read_csv('data.csv')

Saving data.csv to data.csv
Fichier "data.csv" téléchargé.

In [3]:
df["email"].head()

0     malders0@shop-pro.jp
1       hharridge1@gnu.org
2    ekilminster2@etsy.com
3         gbrantl3@umn.edu
4      kbeasant4@jigsy.com
Name: email, dtype: object

In [4]:
df.email.head()

0     malders0@shop-pro.jp
1       hharridge1@gnu.org
2    ekilminster2@etsy.com
3         gbrantl3@umn.edu
4      kbeasant4@jigsy.com
Name: email, dtype: object

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
type(df.email)

pandas.core.series.Series

In [7]:
df[10:13]

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
10,11,03/11/2021,Lief,Woodcraft,lwoodcrafta@sitemeter.com,Male,201.76.240.51,Canada,$5.71,NaN
11,12,03/16/2021,Bailie,Wyman,bwymanb@lulu.com,Male,222.60.138.222,United States,$3.15,20.0
12,13,03/05/2021,Janice,Morillas,jmorillasc@miibeian.gov.cn,Female,24.25.198.252,Canada,$5.30,20.0

In [8]:
df.loc[10:13]

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
10,11,03/11/2021,Lief,Woodcraft,lwoodcrafta@sitemeter.com,Male,201.76.240.51,Canada,$5.71,NaN
11,12,03/16/2021,Bailie,Wyman,bwymanb@lulu.com,Male,222.60.138.222,United States,$3.15,20.0
12,13,03/05/2021,Janice,Morillas,jmorillasc@miibeian.gov.cn,Female,24.25.198.252,Canada,$5.30,20.0
13,14,03/24/2021,Cull,Vassie,cvassied@unblog.fr,NaN,18.203.61.94,France,$5.97,20.0

In [9]:
df_email = df.set_index("email")
df_email.loc['cvassied@unblog.fr'].values.tolist()

[np.int64(14),
 '03/24/2021',
 'Cull',
 'Vassie',
 nan,
 '18.203.61.94',
 'France',
 '$5.97',
 np.float64(20.0)]

In [10]:
df_email.loc[['cvassied@unblog.fr', 'eallawayg@ebay.co.uk']]

,id,date,first_name,last_name,gender,ip_address,country,price_paid,tax
email,,,,,,,,,
cvassied@unblog.fr,14,03/24/2021,Cull,Vassie,NaN,18.203.61.94,France,$5.97,20.0
eallawayg@ebay.co.uk,17,03/27/2021,Eve,Allaway,Female,184.107.59.156,United States,$6.44,20.0