In [2]:
# @title
from google.colab import files

uploaded = files.upload()

file_name = None
if uploaded:
  for fn in uploaded.keys():
    print(f'Fichier "{fn}" téléchargé.')
    file_name = fn
else:
  print("Aucun fichier n'a été téléchargé. Veuillez le télécharger manuellement ou exécuter cette cellule à nouveau.")
  # @title
import pandas as pd
df = pd.read_csv('data.csv')

Saving data.csv to data.csv
Fichier "data.csv" téléchargé.

In [3]:
df_revison = df.copy()

In [4]:
df.drop('ip_address', axis=1, inplace=True)

In [5]:
df

,id,date,first_name,last_name,email,gender,country,price_paid,tax
0,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,Male,Canada,$5.36,NaN
1,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Female,Canada,$8.32,NaN
2,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,Male,United States,$3.73,20.0
3,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,Female,United States,$3.70,20.0
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,Morocco,$9.24,20.0
...,...,...,...,...,...,...,...,...,...
995,996,03/24/2021,Duff,Errigo,derrigorn@elpais.com,Female,France,$3.63,NaN
996,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,Female,NaN,$4.59,20.0
997,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,Male,United States,$7.54,20.0
998,999,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,Male,United States,$5.81,NaN
999,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,NaN,Canada,$8.01,20.0

In [6]:
df.set_index("gender", inplace=True)

In [7]:
df

,id,date,first_name,last_name,email,country,price_paid,tax
gender,,,,,,,,
Male,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,Canada,$5.36,NaN
Female,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Canada,$8.32,NaN
Male,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,United States,$3.73,20.0
Female,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,United States,$3.70,20.0
Male,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Morocco,$9.24,20.0
...,...,...,...,...,...,...,...,...
Female,996,03/24/2021,Duff,Errigo,derrigorn@elpais.com,France,$3.63,NaN
Female,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,NaN,$4.59,20.0
Male,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,United States,$7.54,20.0
Male,999,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,United States,$5.81,NaN
NaN,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,Canada,$8.01,20.0

In [8]:
df.drop("Male", axis=0, inplace=True)

In [9]:
df.head()

,id,date,first_name,last_name,email,country,price_paid,tax
gender,,,,,,,,
Female,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Canada,$8.32,NaN
Female,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,United States,$3.70,20.0
Female,6,03/25/2021,Titos,Braybrooke,tbraybrooke5@umn.edu,United States,$5.82,NaN
Female,7,03/14/2021,Ava,Kencott,akencott6@phoca.cz,Canada,$6.29,NaN
Female,13,03/05/2021,Janice,Morillas,jmorillasc@miibeian.gov.cn,Canada,$5.30,20.0

In [10]:
df.drop(["first_name", "last_name", "email"], axis=1, inplace=True)

In [11]:
df

          id        date        country price_paid   tax
gender
Female     2  03/19/2021         Canada      $8.32   NaN
Female     4  03/19/2021  United States      $3.70  20.0
Female     6  03/25/2021  United States      $5.82   NaN
Female     7  03/14/2021         Canada      $6.29   NaN
Female    13  03/05/2021         Canada      $5.30  20.0
...      ...         ...            ...        ...   ...
NaN      990  03/16/2021         France      $8.69  20.0
Female   995  03/17/2021         France      $5.68  20.0
Female   996  03/24/2021         France      $3.63   NaN
Female   997  03/17/2021            NaN      $4.59  20.0
NaN     1000  03/23/2021         Canada      $8.01  20.0

[562 rows x 5 columns]

In [12]:
del df["id"]

In [13]:
df

              date        country price_paid   tax
gender
Female  03/19/2021         Canada      $8.32   NaN
Female  03/19/2021  United States      $3.70  20.0
Female  03/25/2021  United States      $5.82   NaN
Female  03/14/2021         Canada      $6.29   NaN
Female  03/05/2021         Canada      $5.30  20.0
...            ...            ...        ...   ...
NaN     03/16/2021         France      $8.69  20.0
Female  03/17/2021         France      $5.68  20.0
Female  03/24/2021         France      $3.63   NaN
Female  03/17/2021            NaN      $4.59  20.0
NaN     03/23/2021         Canada      $8.01  20.0

[562 rows x 4 columns]