In [1]:
# @title
from google.colab import files

uploaded = files.upload()

file_name = None
if uploaded:
  for fn in uploaded.keys():
    print(f'Fichier "{fn}" téléchargé.')
    file_name = fn
else:
  print("Aucun fichier n'a été téléchargé. Veuillez le télécharger manuellement ou exécuter cette cellule à nouveau.")
  # @title
import pandas as pd
df = pd.read_csv('data.csv')

Saving data.csv to data.csv
Fichier "data.csv" téléchargé.

In [9]:
df.isnull()

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
0,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,True
996,False,False,False,False,False,False,False,True,False,False
997,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,True
999,False,False,False,False,False,True,False,False,False,False

In [8]:
df.notnull()

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
0,True,True,True,True,True,True,True,True,True,False
1,True,True,True,True,True,True,True,True,True,False
2,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...
995,True,True,True,True,True,True,True,True,True,False
996,True,True,True,True,True,True,True,False,True,True
997,True,True,True,True,True,True,True,True,True,True
998,True,True,True,True,True,True,True,True,True,False
999,True,True,True,True,True,False,True,True,True,True

In [15]:
df[df["tax"].notnull()]

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
2,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,Male,213.8.101.145,United States,$3.73,20.0
3,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,Female,5.140.237.101,United States,$3.70,20.0
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,106.252.162.233,Morocco,$9.24,20.0
7,8,03/08/2021,Codi,Feasley,cfeasley7@ed.gov,Male,26.190.191.249,France,$3.01,20.0
8,9,03/09/2021,Waylon,Heersema,wheersema8@tumblr.com,Male,63.242.174.112,Canada,$3.70,20.0
...,...,...,...,...,...,...,...,...,...,...
991,992,03/07/2021,Elihu,Crush,ecrushrj@berkeley.edu,Male,174.38.173.53,Morocco,$5.05,20.0
994,995,03/17/2021,Carolyne,Bruntjen,cbruntjenrm@reference.com,Female,7.29.168.78,France,$5.68,20.0
996,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,Female,188.219.12.109,NaN,$4.59,20.0
997,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,Male,199.80.60.87,United States,$7.54,20.0
999,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,NaN,170.193.249.83,Canada,$8.01,20.0

In [17]:
df["tax"].fillna(method='bfill')
df["tax"].fillna(0)

/tmp/ipykernel_10411/531617208.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["tax"].fillna(method='bfill')

0      20.0
1      20.0
2      20.0
3      20.0
4      20.0
       ...
995    20.0
996    20.0
997    20.0
998    20.0
999    20.0
Name: tax, Length: 1000, dtype: float64

In [19]:
df.dropna(subset=['tax'])

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
2,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,Male,213.8.101.145,United States,$3.73,20.0
3,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,Female,5.140.237.101,United States,$3.70,20.0
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,106.252.162.233,Morocco,$9.24,20.0
7,8,03/08/2021,Codi,Feasley,cfeasley7@ed.gov,Male,26.190.191.249,France,$3.01,20.0
8,9,03/09/2021,Waylon,Heersema,wheersema8@tumblr.com,Male,63.242.174.112,Canada,$3.70,20.0
...,...,...,...,...,...,...,...,...,...,...
991,992,03/07/2021,Elihu,Crush,ecrushrj@berkeley.edu,Male,174.38.173.53,Morocco,$5.05,20.0
994,995,03/17/2021,Carolyne,Bruntjen,cbruntjenrm@reference.com,Female,7.29.168.78,France,$5.68,20.0
996,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,Female,188.219.12.109,NaN,$4.59,20.0
997,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,Male,199.80.60.87,United States,$7.54,20.0
999,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,NaN,170.193.249.83,Canada,$8.01,20.0