In [1]:
# @title
from google.colab import files

uploaded = files.upload()

file_name = None
if uploaded:
  for fn in uploaded.keys():
    print(f'Fichier "{fn}" téléchargé.')
    file_name = fn
else:
  print("Aucun fichier n'a été téléchargé. Veuillez le télécharger manuellement ou exécuter cette cellule à nouveau.")
  # @title
import pandas as pd
df = pd.read_csv('data.csv')

Saving data.csv to data.csv
Fichier "data.csv" téléchargé.

In [2]:
df["tax"].fillna(0, inplace=True)

/tmp/ipykernel_10361/1359472388.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["tax"].fillna(0, inplace=True)

In [3]:
df

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
0,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,Male,160.119.8.119,Canada,$5.36,0.0
1,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Female,210.51.172.132,Canada,$8.32,0.0
2,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,Male,213.8.101.145,United States,$3.73,20.0
3,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,Female,5.140.237.101,United States,$3.70,20.0
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,106.252.162.233,Morocco,$9.24,20.0
...,...,...,...,...,...,...,...,...,...,...
995,996,03/24/2021,Duff,Errigo,derrigorn@elpais.com,Female,193.84.247.144,France,$3.63,0.0
996,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,Female,188.219.12.109,NaN,$4.59,20.0
997,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,Male,199.80.60.87,United States,$7.54,20.0
998,999,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,Male,0.183.63.11,United States,$5.81,0.0
999,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,NaN,170.193.249.83,Canada,$8.01,20.0

In [4]:
df.price_paid = df.price_paid.apply(lambda x: x.replace('$', ''))
df.price_paid = df.price_paid.astype(float)

In [6]:
df

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
0,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,Male,160.119.8.119,Canada,5.36,0.0
1,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Female,210.51.172.132,Canada,8.32,0.0
2,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,Male,213.8.101.145,United States,3.73,20.0
3,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,Female,5.140.237.101,United States,3.70,20.0
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,106.252.162.233,Morocco,9.24,20.0
...,...,...,...,...,...,...,...,...,...,...
995,996,03/24/2021,Duff,Errigo,derrigorn@elpais.com,Female,193.84.247.144,France,3.63,0.0
996,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,Female,188.219.12.109,NaN,4.59,20.0
997,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,Male,199.80.60.87,United States,7.54,20.0
998,999,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,Male,0.183.63.11,United States,5.81,0.0
999,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,NaN,170.193.249.83,Canada,8.01,20.0

In [18]:
# df["price_total"] = df["price_paid"] * (100 - df["price_paid"]) / 100 OU
df["price_total"] = df["price_paid"] * (1 - df["tax"] / 100)

In [19]:
df

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax,price_total
0,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,Male,160.119.8.119,Canada,5.36,0.0,5.360
1,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Female,210.51.172.132,Canada,8.32,0.0,8.320
2,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,Male,213.8.101.145,United States,3.73,20.0,2.984
3,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,Female,5.140.237.101,United States,3.70,20.0,2.960
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,106.252.162.233,Morocco,9.24,20.0,7.392
...,...,...,...,...,...,...,...,...,...,...,...
995,996,03/24/2021,Duff,Errigo,derrigorn@elpais.com,Female,193.84.247.144,France,3.63,0.0,3.630
996,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,Female,188.219.12.109,NaN,4.59,20.0,3.672
997,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,Male,199.80.60.87,United States,7.54,20.0,6.032
998,999,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,Male,0.183.63.11,United States,5.81,0.0,5.810
999,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,NaN,170.193.249.83,Canada,8.01,20.0,6.408

In [25]:
counties = {"United States": "UN", "France":"FR", "Canada": "CA", "Morocco": "MA"}
df["country_code"] = df['country'].map(counties)

In [26]:
df

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax,price_total,country_code
0,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,Male,160.119.8.119,Canada,5.36,0.0,5.360,CA
1,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Female,210.51.172.132,Canada,8.32,0.0,8.320,CA
2,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,Male,213.8.101.145,United States,3.73,20.0,2.984,UN
3,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,Female,5.140.237.101,United States,3.70,20.0,2.960,UN
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,106.252.162.233,Morocco,9.24,20.0,7.392,MA
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,03/24/2021,Duff,Errigo,derrigorn@elpais.com,Female,193.84.247.144,France,3.63,0.0,3.630,FR
996,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,Female,188.219.12.109,NaN,4.59,20.0,3.672,NaN
997,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,Male,199.80.60.87,United States,7.54,20.0,6.032,UN
998,999,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,Male,0.183.63.11,United States,5.81,0.0,5.810,UN
999,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,NaN,170.193.249.83,Canada,8.01,20.0,6.408,CA