In [ ]:
# ============================================
# 1. IMPORT ET CHARGEMENT DU FICHIER CSV
# ============================================

from google.colab import files
import pandas as pd

# Télécharger le fichier CSV
uploaded = files.upload()

file_name = None
if uploaded:
    for fn in uploaded.keys():
        print(f'Fichier "{fn}" téléchargé.')
        file_name = fn
else:
    print("Aucun fichier n'a été téléchargé. Veuillez le télécharger manuellement ou exécuter cette cellule à nouveau.")

# Charger le fichier CSV dans un DataFrame pandas
df = pd.read_csv('exo.csv')
print(f"DataFrame chargé avec succès ! Dimensions: {df.shape}")

Saving exo.csv to exo.csv
Fichier "exo.csv" téléchargé.

In [ ]:
# ============================================
# 2. NETTOYAGE DES DONNÉES - COLONNE PRIX
# ============================================

# Convertir la colonne prix_dollars en string, supprimer le symbole '$', puis convertir en float
df['prix_dollars'] = df['prix_dollars'].astype(str).apply(lambda x: x.replace('$', ''))
df['prix_dollars'] = df['prix_dollars'].astype(float)

print("✓ Symboles '$' supprimés et données converties en float")
print(f"Aperçu des prix:\n{df['prix_dollars'].head()}")

In [ ]:
# Calculer la moyenne des prix (arrondie à 2 décimales)
# Cette valeur sera utilisée pour remplacer les prix manquants
moyenne_prix = df['prix_dollars'].mean().round(2)
print(f"Moyenne des prix: ${moyenne_prix}")

In [ ]:
# Remplacer les valeurs manquantes (NaN) par la moyenne calculée
df['prix_dollars'].fillna(moyenne_prix, inplace=True)
print(f"✓ Valeurs manquantes remplies avec la moyenne: ${moyenne_prix}")
print(f"Nombre de valeurs manquantes restantes: {df['prix_dollars'].isna().sum()}")

/tmp/ipykernel_12592/2505438407.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['prix_dollars'].fillna(moyenne_prix, inplace=True)

In [ ]:
# Afficher le DataFrame après nettoyage
print("DataFrame après nettoyage des prix:")
df

      produit     pays  prix_dollars genre
0  Chaussures   France        100.00     F
1     Maillot   Canada         45.00     M
2      Ballon   France         25.00     M
3       Short  Belgium         56.67     F

In [ ]:
# ============================================
# 3. ENRICHISSEMENT DES DONNÉES - CODES PAYS
# ============================================

# Créer un dictionnaire de correspondance pays -> codes ISO
abreviation = {'France': 'FR', 'Canada': 'CA', 'Belgium': 'BE'}

# Ajouter une nouvelle colonne avec les codes pays
df['codes_pays'] = df['pays'].map(abreviation)
print("✓ Colonne 'codes_pays' ajoutée")
print(f"Codes pays uniques: {df['codes_pays'].unique()}")

In [ ]:
# Afficher le DataFrame avec la nouvelle colonne
print("DataFrame avec codes pays:")
df

      produit     pays  prix_dollars genre codes_pays
0  Chaussures   France        100.00     F         FR
1     Maillot   Canada         45.00     M         CA
2      Ballon   France         25.00     M         FR
3       Short  Belgium         56.67     F         BE

In [ ]:
# ============================================
# 4. ANALYSE DES DONNÉES
# ============================================

# Calculer la somme des prix par genre
prix_par_genre = df.groupby('genre')['prix_dollars'].sum()
print("Somme des prix par genre:")
prix_par_genre

genre
F    156.67
M     70.00
Name: prix_dollars, dtype: float64

In [ ]:
# ============================================
# 5. CONVERSION EN EUROS
# ============================================

# Convertir les prix de dollars en euros (taux: 1$ = 0.92€)
df['prix_euros'] = (df['prix_dollars'] * 0.92).round(0)
print("✓ Colonne 'prix_euros' ajoutée (taux: 1$ = 0.92€)")

In [ ]:
# Afficher le DataFrame final avec toutes les transformations
print("=" * 50)
print("DONNÉES FINALES")
print("=" * 50)
df

      produit     pays  prix_dollars genre codes_pays  prix_euros
0  Chaussures   France        100.00     F         FR        92.0
1     Maillot   Canada         45.00     M         CA        41.0
2      Ballon   France         25.00     M         FR        23.0
3       Short  Belgium         56.67     F         BE        52.0